#  Main header!
#  Line 2

[songs]
	[songs.a_familiar_room]
		triggers = [ "dimension-overworld" ]
	[songs.creator]
		triggers = [ "dimension-overworld" ]
	[songs.csinom_palko]
		triggers = [ "dimension-overworld", "zones-corino" ]
	[songs.daddys_cassette]
		triggers = [ "dimension-overworld" ]
	[songs.deeper]
		triggers = [ "dimension-overworld" ]
	[songs.echo_in_the_wind]
		triggers = [ "dimension-overworld" ]
	[songs.fieldday]
		triggers = [ "dimension-overworld" ]
	[songs.final_duet]
		triggers = [ "zones-pavia_theatre", "dimension-overworld" ]
	[songs.for_river]
		triggers = [ "zones-pavia_theatre", "dimension-overworld" ]
	[songs.inno_al_re]
		triggers = [ "dimension-overworld", "zones-rozzano" ]
		volume = 0.5
		[songs.inno_al_re.loop]
			loop_count = 1
			to = 14000
	[songs.left_to_bloom]
		triggers = [ "dimension-overworld" ]
	[songs.lurelin_village]
		triggers = [ "dimension-overworld" ]
	[songs.mountain]
		triggers = [ "dimension-overworld" ]
	[songs.mountains]
		triggers = [ "dimension-overworld" ]
	[songs.se_il_papa]
		triggers = [ "dimension-overworld", "zones-villana" ]
	[songs.tarrey_town]
		triggers = [ "zones-pavia_bedford", "dimension-overworld" ]
	[songs.time]
		triggers = [ "dimension-overworld" ]
	[songs.tornado_siren]
		triggers = [ "dimension-overworld", "zones-pavia_vault" ]
	[songs.travelers]
		triggers = [ "dimension-overworld" ]
	[songs.youngn]
		triggers= [ "dimension-overworld" "zones-ssg_cabin" ]
	[songs.universal]
		pitch = 1.0
		play_once = 0
		speed = 1.0
		volume = 0.5
		[songs.universal.interrupt_handler]
			priority = 2147483647
			trigger_whitelist = [ ]
	[songs.lofi]
		triggers = [ "dimension-overworld" "zones-fempire" ]
		volume = 1.0
	[songs.we_all_lift]
		triggers = [ "dimension-overworld" "zones-fempire" ]
	[songs.comfortably_numb]
		triggers = [ "dimension-overworld" "zones-yngland" ]
	[songs.another_brick]
		triggers = [ "dimension-overworld" "zones-yngland" ]
	[songs.stairway_to_heaven]
		triggers = [ "dimension-overworld" "zones-yngland" ]
	[songs.this_fire]
		triggers = [ "dimension-overworld" "zones-yngland" ]
	[songs.magical_mystery_tour]
		triggers = [ "dimension-overworld" "zones-yngland" ]
	[songs.house_of_the_rising_sun]
		triggers = [ "dimension-overworld" "zones-yngland" ]
	[songs.paint_it_black]
		triggers = [ "dimension-overworld" "zones-yngland" ]
	[songs.dream_on]
		triggers = [ "dimension-overworld" "zones-yngland" ]
	[songs.sympathy_for_the_devil]
		triggers = [ "dimension-overworld" "zones-yngland" ]
	[songs.the_reaper]
		triggers = [ "dimension-overworld" "zones-yngland" ]
	[songs.civradio]
		triggers = [ "dimension-overworld" "zones-icenia_radio" ]
		volume = 2
	[songs.a_thousand_greetings]
		triggers = ["dimension-overworld" "zones-khalkedonia" ]

	[songs.requiem]
		triggers = ["dimension-overworld" "zones-khalkedonia" ]

	[songs.sands_of_tide]
		triggers = ["dimension-overworld" "zones-khalkedonia" ]

	[songs.heaven_pierce_her]
		triggers = ["dimension-overworld" "zones-khalkedonia" ]

	[songs.the_world_looks_white]
		triggers = ["dimension-overworld" "zones-khalkedonia" ]

	[songs.the_sacred_war]
		triggers = ["dimension-overworld" "zones-khalkedonia" ]

	[songs.chinese_instrumental]
		triggers = ["dimension-overworld" "zones-khalkedonia" ]



[triggers]
	[[triggers.dimension]]
		identifier = "nether"
		resource_name = [ "nether" ]
	[[triggers.dimension]]
		identifier = "overworld"
		resource_name = [ "overworld" ]
	[triggers.universal]
		active_cooldown = "0"
		fade_in = "50"
		fade_out = "50"
		persistence = "40"
		ticks_before_active = "0"
		ticks_before_audio = "0"
		ticks_between_audio = "4000"
	[[triggers.zones]]
		identifier = "pavia_vault"
		priority = 3600
		zone_max_x = 1125
		zone_max_y = 300
		zone_max_z = "-2990"
		zone_min_x = 1038
		zone_min_y = 20
		zone_min_z = "-3090"
	[[triggers.zones]]
		identifier = "pavia"
		priority = 3500
		zone_max_x = 900
		zone_max_y = 300
		zone_max_z = "-2790"
		zone_min_x = 550
		zone_min_y = 40
		zone_min_z = "-3200"
	[[triggers.zones]]
		identifier = "pavia_bedford"
		priority = 3600
		zone_max_x = 1332
		zone_max_y = 110
		zone_max_z = "-2689"
		zone_min_x = 942
		zone_min_y = 50
		zone_min_z = "-2901"
	[[triggers.zones]]
		identifier = "pavia_theatre"
		priority = 3600
		zone_max_x = 861
		zone_max_y = 110
		zone_max_z = "-3210"
		zone_min_x = 790
		zone_min_y = 50
		zone_min_z = "-3250"
	[[triggers.zones]]
		identifier = "villana"
		priority = 3500
		zone_max_x = 1407
		zone_max_y = 200
		zone_max_z = 9219
		zone_min_x = 1150
		zone_min_y = 40
		zone_min_z = 9015
	[[triggers.zones]]
		identifier = "corino"
		priority = 3500
		zone_max_x = 2560
		zone_max_y = 200
		zone_max_z = 9360
		zone_min_x = 2192
		zone_min_y = 40
		zone_min_z = 9001
	[[triggers.zones]]
		identifier = "rozzano"
		priority = 3500
		zone_max_x = 2134
		zone_max_y = 200
		zone_max_z = 9572
		zone_min_x = 1550
		zone_min_y = 40
		zone_min_z = 9190
	[[triggers.zones]]
		identifier = "ssg_cabin"
		priority = 3500
		zone_max_x = 2036
		zone_max_y = 77
		zone_max_z = 7247
		zone_min_x = 2025
		zone_min_y = 70
		zone_min_z = 7232
	[[triggers.zones]]
		identifier = "fempire"
		priority = 3500
		zone_max_x = 6523
		zone_max_y = 200
		zone_max_z = "-5947"
		zone_min_x = 5540
		zone_min_y = 40
		zone_min_z = "-6891"
		zone_min_z = 7232
	[[triggers.zones]]
		identifier = "yngland"
		priority = 3500
		zone_max_x = 5640
		zone_max_y = 200
		zone_max_z = "-7101"
		zone_min_x = 5380
		zone_min_y = 40
		zone_min_z = "-7280"
	[[triggers.zones]]
		identifier = "icenia_radio"
		priority = 3600
		zone_max_x = "-3600"
		zone_max_y = 200
		zone_max_z = "-4120"
		zone_min_x = "-4000"
		zone_min_y = 40
		zone_min_z = "-4520"		zone_min_z = "-4520"
	[[triggers.zones]]
		identifier = "khalkedonia"
		priority = 3500
		zone_max_x = 8032
		zone_max_y = 200
		zone_max_z = "-4170"
		zone_min_x = 7638
		zone_min_y = 40
		zone_min_z = "-4863"